# Generated by Django 3.2.7 on 2021-09-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_permision_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permision_level',
            new_name='permission_level',
        ),
    ]
