# Generated by Django 3.2.7 on 2021-09-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_block_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(unique=True),
        ),
    ]
