# Generated by Django 3.2.6 on 2021-08-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('sender', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('transaction_fee', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
            ],
        ),
    ]
