# Generated by Django 3.2.6 on 2021-08-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210829_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
