# Generated by Django 3.2.6 on 2021-08-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
