# Generated by Django 3.2.7 on 2021-09-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_rename_status_token_active'),
        ('transactions', '0005_remove_transaction_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.token'),
        ),
    ]
