# Generated by Django 3.2.7 on 2021-09-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210913_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='input',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
