# Generated by Django 3.2.7 on 2021-09-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
