# Generated by Django 3.2.7 on 2021-09-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='block',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
