# Generated by Django 3.2.7 on 2021-10-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_hexadecimal',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
