# Generated by Django 3.2.7 on 2021-09-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='alias',
            field=models.CharField(default='', max_length=100),
        ),
    ]
