# Generated by Django 3.2.7 on 2021-09-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_rename_status_token_active'),
        ('wallets', '0002_wallet_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='tokens',
            field=models.ManyToManyField(to='tokens.Token'),
        ),
    ]
