# Generated by Django 3.2.7 on 2021-09-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
