# Generated by Django 3.2.7 on 2021-09-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_token_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='status',
            new_name='active',
        ),
    ]
