# Generated by Django 3.2.7 on 2021-09-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_rename_status_token_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='abi',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
