# Generated by Django 3.2.7 on 2021-09-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_token_abi'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='image',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
