# Generated by Django 3.2.7 on 2021-09-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_token_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
