# Generated by Django 3.2.7 on 2021-09-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_alter_token_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
