# Generated by Django 3.2.7 on 2021-09-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_alter_token_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='abi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
