# Generated by Django 3.2.7 on 2021-10-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0009_token_total_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='total_supply',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
