# Generated by Django 3.2.7 on 2021-10-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0010_alter_token_total_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
