# Generated by Django 3.2.7 on 2021-10-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0011_token_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='total_supply',
            new_name='supply',
        ),
    ]
