# Generated by Django 3.2.7 on 2021-10-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0012_rename_total_supply_token_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='total',
        ),
    ]
