# Generated by Django 3.2.7 on 2021-10-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0014_token_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='coingecko_id',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
